services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.19.0@sha256:fefb27166f5e1611ebf67f8697ea928a23f44efdb00af922e2ac3b5faa2efd5c
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    environment:
      - APP_URL=http://localhost:8090

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.18.8@sha256:3b1939746690e423072b4a99bf4c4af6dd9562a68978a33738a3c4a4cc000c39
    restart: unless-stopped
    volumes:
      - beszel_socket:/beszel_socket
      - var_lib_beszel_agent:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HUB_URL=http://beszel:8090
      - LISTEN=/beszel_socket/beszel.sock
    env_file:
      - .env
    depends_on:
      - beszel

volumes:
  beszel_data:
  beszel_socket:
  var_lib_beszel_agent:
