x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  home-assistant:
    <<: *default-logging
    image: ghcr.io/home-assistant/home-assistant:2026.9.2
    container_name: home-assistant
    network_mode: host
    volumes:
      - /srv/home-assistant/config:/config
    restart: unless-stopped

  matterjs-server:
    <<: *default-logging
    image: ghcr.io/matter-js/matterjs-server:1.4.0
    container_name: matterjs-server
    network_mode: host
    volumes:
      - /srv/matter-js/data:/data
    privileged: true
    restart: unless-stopped
