x-logging: &default-logging
  logging:
    driver: local
    options:
      max-file: 3
      max-size: 10m

services:
  beszel:
    <<: *default-logging
    container_name: beszel
    image: henrygd/beszel:0.19.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - /run/beszel:/beszel_socket
      - /srv/beszel/data:/beszel_data

  beszel-agent:
    <<: *default-logging
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.19.0
    restart: unless-stopped
    environment:
      - HUB_URL=http://beszel:8090
      - KEY=${BESZEL_KEY}
      - LISTEN=/beszel_socket/beszel.sock
      - TOKEN=${BESZEL_TOKEN}
    volumes:
      - /run/beszel:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock

  homepage:
    <<: *default-logging
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    network_mode: host
    volumes:
      - ./homepage-settings.yaml:/app/config/settings.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro

  home-assistant:
    <<: *default-logging
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2026.9.2
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./home_assistant_config:/config

  matterjs-server:
    <<: *default-logging
    container_name: matterjs-server
    image: ghcr.io/matter-js/matterjs-server:1.4.0
    restart: unless-stopped
    user: 0:0
    network_mode: host
    volumes:
      - ./matterjs_server_data:/data
