services:
  home-assistant:
    image: homeassistant/home-assistant:2026.8.3
    restart: unless-stopped
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

volumes:
  config:
