services:
  knot-resolver:
    image: cznic/knot-resolver:v6.4.2
    restart: unless-stopped
    volumes:
      - /var/cache/knot-resolver:/var/cache/knot-resolver
      - ./config.yaml:/etc/knot-resolver/config.yaml
